/*
Purpose:
This file implements the make:event, make:job, make:policy, and make:provider
CLI scaffolding commands for the GoStack framework.

Philosophy:
Every subsystem should have a corresponding generator so developers never need to
write boilerplate from scratch. These generators follow the same pattern as the
existing make:controller and make:middleware commands — each produces a well-commented,
idiomatic Go source file under the appropriate internal/ subdirectory.

Architecture:
Implements console.Command. Each command uses text/template + go/format to produce
syntactically valid, package-correct Go source files.

Commands:
  - make:event    → internal/events/<Name>Event.go
  - make:job      → internal/jobs/<Name>Job.go
  - make:policy   → internal/policies/<Name>Policy.go
  - make:provider → internal/providers/<Name>ServiceProvider.go
*/
package console

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// ─── make:event ────────────────────────────────────────────────────────────────

// MakeEventCommand scaffolds a new event class under internal/events/.
type MakeEventCommand struct{}

func (c *MakeEventCommand) Name() string        { return "make:event" }
func (c *MakeEventCommand) Description() string { return "Scaffold a new event class (Usage: make:event <Name>)" }

const eventStub = `// Code generated by GoStack make:event. Feel free to edit.
package events

import "time"

// {{.Name}}Event is raised when {{.Lower}} occurs in the application.
// Register listeners for this event in your EventServiceProvider.
type {{.Name}}Event struct {
	// OccurredAt records the time the event was raised.
	OccurredAt time.Time

	// TODO: Add your event payload fields here.
	// Example:
	//   UserID int
	//   Email  string
}

// New{{.Name}}Event creates a new {{.Name}}Event with the current timestamp.
func New{{.Name}}Event() *{{.Name}}Event {
	return &{{.Name}}Event{OccurredAt: time.Now()}
}
`

func (c *MakeEventCommand) Execute(args []string) error {
	if len(args) == 0 {
		return fmt.Errorf("usage: make:event <EventName>")
	}
	name := toStudlyCase(args[0])
	name = strings.TrimSuffix(name, "Event") // Normalize: avoid double "Event"

	dir := filepath.Join("internal", "events")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create directory %s: %w", dir, err)
	}

	filename := filepath.Join(dir, name+"Event.go")
	if _, err := os.Stat(filename); err == nil {
		return fmt.Errorf("event already exists: %s", filename)
	}

	data := struct {
		Name  string
		Lower string
	}{
		Name:  name,
		Lower: strings.ToLower(name),
	}
	return renderStub(filename, eventStub, data)
}

// ─── make:job ──────────────────────────────────────────────────────────────────

// MakeJobCommand scaffolds a new dispatchable job under internal/jobs/.
type MakeJobCommand struct{}

func (c *MakeJobCommand) Name() string        { return "make:job" }
func (c *MakeJobCommand) Description() string { return "Scaffold a new queue job class (Usage: make:job <Name>)" }

const jobStub = `// Code generated by GoStack make:job. Feel free to edit.
package jobs

import "fmt"

// {{.Name}}Job is a dispatchable unit of background work.
// Push it onto the queue via gostack.Queue().Push(&{{.Name}}Job{}).
type {{.Name}}Job struct {
	// TODO: Add the fields your job needs to carry its payload.
	// Example:
	//   UserID int
	//   Email  string
}

// Handle executes the job logic. It is called by the queue worker.
// Return a non-nil error to mark the job as failed (it may be retried
// depending on the queue configuration).
func (j *{{.Name}}Job) Handle() error {
	fmt.Println("[Job] Handling {{.Name}}Job…")
	// TODO: implement job logic here.
	return nil
}

// MaxRetries returns how many times this job should be retried on failure.
// Return 0 to disable retries.
func (j *{{.Name}}Job) MaxRetries() int { return 3 }
`

func (c *MakeJobCommand) Execute(args []string) error {
	if len(args) == 0 {
		return fmt.Errorf("usage: make:job <JobName>")
	}
	name := toStudlyCase(args[0])
	name = strings.TrimSuffix(name, "Job")

	dir := filepath.Join("internal", "jobs")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create directory %s: %w", dir, err)
	}

	filename := filepath.Join(dir, name+"Job.go")
	if _, err := os.Stat(filename); err == nil {
		return fmt.Errorf("job already exists: %s", filename)
	}

	data := struct{ Name string }{Name: name}
	return renderStub(filename, jobStub, data)
}

// ─── make:policy ───────────────────────────────────────────────────────────────

// MakePolicyCommand scaffolds a new authorization policy under internal/policies/.
type MakePolicyCommand struct{}

func (c *MakePolicyCommand) Name() string        { return "make:policy" }
func (c *MakePolicyCommand) Description() string { return "Scaffold a new authorization policy (Usage: make:policy <Name>)" }

const policyStub = `// Code generated by GoStack make:policy. Feel free to edit.
package policies

// {{.Name}}Policy defines authorization rules for {{.Lower}}-related actions.
// Methods return true to allow, false to deny.
// Register this policy in your AuthServiceProvider.
type {{.Name}}Policy struct{}

// View returns true if the actor is permitted to view a {{.Lower}}.
func (p *{{.Name}}Policy) View(actorID int, resourceID int) bool {
	// TODO: implement
	return true
}

// Create returns true if the actor is permitted to create a {{.Lower}}.
func (p *{{.Name}}Policy) Create(actorID int) bool {
	// TODO: implement
	return true
}

// Update returns true if the actor is permitted to update the {{.Lower}}.
func (p *{{.Name}}Policy) Update(actorID int, resourceID int) bool {
	// TODO: implement — e.g. return actorID == resourceOwnerID
	return actorID == resourceID
}

// Delete returns true if the actor is permitted to delete the {{.Lower}}.
func (p *{{.Name}}Policy) Delete(actorID int, resourceID int) bool {
	// TODO: implement
	return actorID == resourceID
}
`

func (c *MakePolicyCommand) Execute(args []string) error {
	if len(args) == 0 {
		return fmt.Errorf("usage: make:policy <PolicyName>")
	}
	name := toStudlyCase(args[0])
	name = strings.TrimSuffix(name, "Policy")

	dir := filepath.Join("internal", "policies")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create directory %s: %w", dir, err)
	}

	filename := filepath.Join(dir, name+"Policy.go")
	if _, err := os.Stat(filename); err == nil {
		return fmt.Errorf("policy already exists: %s", filename)
	}

	data := struct {
		Name  string
		Lower string
	}{Name: name, Lower: strings.ToLower(name)}
	return renderStub(filename, policyStub, data)
}

// ─── make:provider ─────────────────────────────────────────────────────────────

// MakeProviderCommand scaffolds a new service provider under internal/providers/.
type MakeProviderCommand struct{}

func (c *MakeProviderCommand) Name() string        { return "make:provider" }
func (c *MakeProviderCommand) Description() string {
	return "Scaffold a new service provider (Usage: make:provider <Name>)"
}

const providerStub = `// Code generated by GoStack make:provider. Feel free to edit.
package providers

// {{.Name}}ServiceProvider bootstraps {{.Lower}}-related services into the GoStack
// application container. Register it in your application's bootstrap file.
//
// Typical usage:
//
//	app.Register(&providers.{{.Name}}ServiceProvider{})
type {{.Name}}ServiceProvider struct{}

// Register binds services into the application container.
// This runs before any service has been booted.
func (p *{{.Name}}ServiceProvider) Register() {
	// TODO: bind services
	// Example:
	//   app.Singleton("{{.Lower}}", func() *MyService { return NewMyService() })
}

// Boot runs after all providers have been registered.
// Use this for actions that depend on other services being available.
func (p *{{.Name}}ServiceProvider) Boot() {
	// TODO: boot logic (optional)
}
`

func (c *MakeProviderCommand) Execute(args []string) error {
	if len(args) == 0 {
		return fmt.Errorf("usage: make:provider <ProviderName>")
	}
	name := toStudlyCase(args[0])
	name = strings.TrimSuffix(name, "ServiceProvider")
	name = strings.TrimSuffix(name, "Provider")

	dir := filepath.Join("internal", "providers")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create directory %s: %w", dir, err)
	}

	filename := filepath.Join(dir, name+"ServiceProvider.go")
	if _, err := os.Stat(filename); err == nil {
		return fmt.Errorf("provider already exists: %s", filename)
	}

	data := struct {
		Name  string
		Lower string
	}{Name: name, Lower: strings.ToLower(name)}
	return renderStub(filename, providerStub, data)
}

// ─── Shared helpers ─────────────────────────────────────────────────────────────

// renderStub parses the template, executes it against data, formats the output
// with gofmt, and writes the result to filename.
func renderStub(filename, stubTemplate string, data any) error {
	tmpl, err := template.New("stub").Parse(stubTemplate)
	if err != nil {
		return fmt.Errorf("template parse error: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("template execute error: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// If gofmt fails (e.g. the stub uses placeholder comments), write raw.
		formatted = buf.Bytes()
	}

	if err := os.WriteFile(filename, formatted, 0644); err != nil {
		return fmt.Errorf("failed to write %s: %w", filename, err)
	}

	fmt.Printf("[GoStack CLI] Created: %s\n", filename)
	return nil
}

// toStudlyCase converts snake_case or kebab-case or plain words to StudlyCase.
// Examples: "user_profile" → "UserProfile", "send-email" → "SendEmail"
func toStudlyCase(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool {
		return r == '_' || r == '-' || r == ' '
	})
	var b strings.Builder
	for _, p := range parts {
		if len(p) == 0 {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]) + p[1:])
	}
	return b.String()
}
