/*
Purpose:
This file implements the Tempose Ahead-of-Time (AOT) component compilation engine.

Philosophy:
GoStack treats frontend components (HTML, CSS, JS) as first-class Go citizens.
Rather than parsing template files at runtime (which introduces disk I/O latency
and defers syntax errors to production), the compiler transforms all component
assets into static Go source code during the build step.

This means the generated file (gostack_components_gen.go) is a standard Go file
that is compiled directly into the application binary. The result is:
  - Zero disk I/O on every HTTP request for view rendering.
  - Compile-time guarantees that all registered components exist.
  - A single, portable binary with all assets embedded.

COMPONENT STRUCTURE:
Each component lives in its own subdirectory under the components path:
	components/
	  counter/
	    counter.html   ← markup template (supports {{ .Field }} bindings)
	    counter.css    ← component-scoped styles
	    counter.js     ← component-specific client scripts

The compiler scans this directory structure, processes each asset type,
and emits a single Go registration file containing all compiled outputs.
*/
package ui

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// AssetCompiler orchestrates the full component compilation pipeline.
// It scans the components source directory, processes all assets (HTML, CSS, JS),
// and writes a fully compiled, Go-formatted registration file to the output path.
//
// Fields:
//   - ComponentsPath: Absolute or relative path to the components source directory.
//   - OutputPath: Absolute or relative path where the generated Go file will be written.
type AssetCompiler struct {
	ComponentsPath string
	OutputPath     string
}

// NewAssetCompiler constructs an AssetCompiler configured with the given source and output paths.
//
// Parameters:
//   - componentsPath: The directory containing component subdirectories (e.g. "templates/components").
//   - outputPath: The directory where "gostack_components_gen.go" will be written (e.g. "cmd/app").
func NewAssetCompiler(componentsPath, outputPath string) *AssetCompiler {
	return &AssetCompiler{ComponentsPath: componentsPath, OutputPath: outputPath}
}

// Run executes the directory sweep and generates a static Go bootstrap asset file.
func (c *AssetCompiler) Run() error {
	entries, err := os.ReadDir(c.ComponentsPath)
	if err != nil {
		return fmt.Errorf("cannot scan components directory: %w", err)
	}

	var registrations strings.Builder
	needsFmt := false
	needsUI := false

	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}

		name := entry.Name()
		componentDir := filepath.Join(c.ComponentsPath, name)

		// 1. Process Scoped CSS
		cssPath := filepath.Join(componentDir, name+".css")
		if _, err := os.Stat(cssPath); err == nil {
			rawCSS, err := os.ReadFile(cssPath)
			if err != nil {
				return err
			}
			prefixed := c.scopeCSS(name, string(rawCSS))
			safeCSS := strings.ReplaceAll(prefixed, "`", "` + \"`\" + `")
			registrations.WriteString(fmt.Sprintf("\tui.RegisterComponentStyle(\"%s\", `%s`)\n\n", name, safeCSS))
			needsUI = true
		}

		// 2. Process JS Scripts
		jsPath := filepath.Join(componentDir, name+".js")
		if _, err := os.Stat(jsPath); err == nil {
			rawJS, err := os.ReadFile(jsPath)
			if err != nil {
				return err
			}
			safeJS := strings.ReplaceAll(string(rawJS), "`", "` + \"`\" + `")
			registrations.WriteString(fmt.Sprintf("\tui.RegisterComponentScript(\"%s\", `%s`)\n\n", name, safeJS))
			needsUI = true
		}

		// 3. Process HTML Templates
		htmlPath := filepath.Join(componentDir, name+".html")
		if _, err := os.Stat(htmlPath); err == nil {
			rawHTML, err := os.ReadFile(htmlPath)
			if err != nil {
				return err
			}
			rawHTMLStr := string(rawHTML)
			if strings.Contains(rawHTMLStr, "{{") {
				needsFmt = true
				needsUI = true
			}
			compiledHTML := c.compileHTML(name, rawHTMLStr)
			registrations.WriteString(fmt.Sprintf("\tt.Register(\"%s\", func(w io.Writer, data any) error {\n%s\t\treturn nil\n\t})\n\n", name, compiledHTML))
		}
	}

	// Build dynamic imports slice
	var imports []string
	if needsFmt {
		imports = append(imports, `"fmt"`)
	}
	imports = append(imports, `"github.com/charledeon77/gostack/framework/http"`)
	if needsUI {
		imports = append(imports, `"github.com/charledeon77/gostack/framework/ui"`)
	}
	imports = append(imports, `"io"`)

	// Generate the actual source file that binds to the user's application binary
	goSource := fmt.Sprintf(`// Code generated by GoStack. DO NOT EDIT.
// This file is compiled from component directories during local development builds.

package main

import (
	%s
)

// RegisterComponents binds all compiled component views, styles, and scripts.
func RegisterComponents(t *http.Tempose) {
%s}`, strings.Join(imports, "\n\t"), registrations.String())

	return os.WriteFile(filepath.Join(c.OutputPath, "gostack_components_gen.go"), []byte(goSource), 0644)
}

// compileHTML transforms a raw HTML template string into a sequence of Go io.WriteString
// calls that can be embedded directly into a compiled ViewFunc.
func (c *AssetCompiler) compileHTML(componentName, rawHTML string) string {
	wrappedHTML := fmt.Sprintf("<div gs-component=\"%s\">\n%s\n</div>", componentName, strings.TrimSpace(rawHTML))
	
	var sb strings.Builder
	parts := strings.Split(wrappedHTML, "{{")
	
	// Write first static part
	firstSafe := strings.ReplaceAll(parts[0], "`", "` + \"`\" + `")
	sb.WriteString(fmt.Sprintf("\t\tif _, err := io.WriteString(w, `%s`); err != nil { return err }\n", firstSafe))
	
	for i := 1; i < len(parts); i++ {
		subparts := strings.Split(parts[i], "}}")
		if len(subparts) < 2 {
			continue
		}
		expr := strings.TrimSpace(subparts[0])
		rest := subparts[1]
		
		if strings.HasPrefix(expr, ".") {
			fieldName := strings.TrimPrefix(expr, ".")
			sb.WriteString(fmt.Sprintf("\t\tif _, err := io.WriteString(w, fmt.Sprint(ui.Evaluate(data, \"%s\"))); err != nil { return err }\n", fieldName))
		} else {
			sb.WriteString(fmt.Sprintf("\t\tif _, err := io.WriteString(w, fmt.Sprint(%s)); err != nil { return err }\n", expr))
		}
		
		restSafe := strings.ReplaceAll(rest, "`", "` + \"`\" + `")
		if restSafe != "" {
			sb.WriteString(fmt.Sprintf("\t\tif _, err := io.WriteString(w, `%s`); err != nil { return err }\n", restSafe))
		}
	}
	return sb.String()
}

// scopeCSS transforms raw CSS into component-scoped CSS by prepending a unique
// selector prefix to every rule block, preventing styles from leaking globally.
func (c *AssetCompiler) scopeCSS(componentName, rawCSS string) string {
	var scoped []string
	prefix := fmt.Sprintf("gostack-root [gs-component=\"%s\"]", componentName)

	lines := strings.Split(rawCSS, "\n")
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "/*") {
			continue
		}
		if strings.Contains(line, "{") && !strings.HasPrefix(line, "@") {
			scoped = append(scoped, prefix+" "+line)
		} else {
			scoped = append(scoped, line)
		}
	}
	return strings.Join(scoped, "\n")
}
