// Code generated by GoStack. DO NOT EDIT.
// This file is compiled from component directories during local development builds.

package main

import (
	"github.com/charledeon77/gostack-framework/framework/http"
	"github.com/charledeon77/gostack-framework/framework/ui"
	"io"
)

// RegisterComponents binds all compiled component views, styles, and scripts.
func RegisterComponents(t *http.Tempose) {
	ui.RegisterComponentStyle("button", `gostack-root [gs-component="button"] .gs-btn {
display: inline-flex;
align-items: center;
justify-content: center;
padding: 0.5rem 1rem;
font-size: 0.875rem;
font-weight: 500;
border-radius: 0.375rem;
border: none;
cursor: pointer;
transition: all 0.2s ease-in-out;
}
gostack-root [gs-component="button"] .gs-btn-primary {
background-color: #0f172a;
color: #ffffff;
}
gostack-root [gs-component="button"] .gs-btn-primary:hover {
background-color: #334155;
}
gostack-root [gs-component="button"] .gs-btn-secondary {
background-color: #f1f5f9;
color: #0f172a;
border: 1px solid #e2e8f0;
}
gostack-root [gs-component="button"] .gs-btn-secondary:hover {
background-color: #e2e8f0;
}
gostack-root [gs-component="button"] .gs-btn-danger {
background-color: #ef4444;
color: #ffffff;
}
gostack-root [gs-component="button"] .gs-btn-danger:hover {
background-color: #dc2626;
}`)

	t.Register("button", func(w io.Writer, data any) error {
		if _, err := io.WriteString(w, `<div gs-component="button">
<div gs-component="button">
    <!-- 
        Accepts variables:
        - variant: 'primary', 'secondary', 'danger'
        - text: Button text 
    -->
    <button class="gs-btn gs-btn-`); err != nil { return err }
		if _, err := io.WriteString(w, ui.Escape(ui.Evaluate(data, "variant"))); err != nil { return err }
		if _, err := io.WriteString(w, `" gs-click="`); err != nil { return err }
		if _, err := io.WriteString(w, ui.Escape(ui.Evaluate(data, "onClick"))); err != nil { return err }
		if _, err := io.WriteString(w, `">
        `); err != nil { return err }
		if _, err := io.WriteString(w, ui.Escape(ui.Evaluate(data, "text"))); err != nil { return err }
		if _, err := io.WriteString(w, `
    </button>
</div>
</div>`); err != nil { return err }
		return nil
	})

	ui.RegisterComponentStyle("counter", `gostack-root [gs-component="counter"] button {
background-color: #0076ff;
color: white;
border: none;
padding: 0.5rem 1rem;
border-radius: 4px;
cursor: pointer;
}
gostack-root [gs-component="counter"] button:hover {
background-color: #0056b3;
}
gostack-root [gs-component="counter"] span {
font-size: 1.5rem;
margin: 0 1rem;
font-weight: bold;
}`)

	ui.RegisterComponentScript("counter", `// counter.js: Custom reactive handlers or initialization for the counter component
console.log('Counter component hydrated successfully');
`)

	t.Register("counter", func(w io.Writer, data any) error {
		if _, err := io.WriteString(w, `<div gs-component="counter">
<div gs-data='{"count": 0}'>
    <button gs-click="count--">-</button>
    <span gs-text="count">0</span>
    <button gs-click="count++">+</button>
</div>
</div>`); err != nil { return err }
		return nil
	})

	ui.RegisterComponentStyle("login", `gostack-root [gs-component="login"] .auth-card {
max-width: 400px;
margin: 50px auto;
padding: 30px;
background: #ffffff;
border-radius: 12px;
box-shadow: 0 4px 20px rgba(0,0,0,0.08);
font-family: 'Inter', sans-serif;
}
gostack-root [gs-component="login"] .auth-card h2 {
margin-top: 0;
margin-bottom: 24px;
color: #1a1a1a;
font-weight: 700;
text-align: center;
}
gostack-root [gs-component="login"] .form-group {
margin-bottom: 20px;
}
gostack-root [gs-component="login"] .form-group label {
display: block;
margin-bottom: 8px;
font-size: 14px;
font-weight: 500;
color: #4a4a4a;
}
gostack-root [gs-component="login"] .form-group input {
width: 100%;
padding: 12px 16px;
border: 1px solid #dcdcdc;
border-radius: 8px;
box-sizing: border-box;
font-size: 15px;
transition: border-color 0.2s;
}
gostack-root [gs-component="login"] .form-group input:focus {
outline: none;
border-color: #4f46e5;
}
gostack-root [gs-component="login"] .btn {
display: block;
width: 100%;
padding: 14px;
background: #4f46e5;
color: #ffffff;
border: none;
border-radius: 8px;
font-size: 16px;
font-weight: 600;
cursor: pointer;
transition: background-color 0.2s;
}
gostack-root [gs-component="login"] .btn:hover {
background: #4338ca;
}
gostack-root [gs-component="login"] .alert {
padding: 12px;
border-radius: 8px;
margin-bottom: 20px;
font-size: 14px;
}
gostack-root [gs-component="login"] .alert:empty {
display: none;
}
gostack-root [gs-component="login"] .alert-danger {
background: #fee2e2;
color: #991b1b;
}
gostack-root [gs-component="login"] .auth-switch {
margin-top: 24px;
text-align: center;
font-size: 14px;
color: #6b7280;
}
gostack-root [gs-component="login"] .auth-switch a {
color: #4f46e5;
text-decoration: none;
font-weight: 500;
}
gostack-root [gs-component="login"] .auth-switch a:hover {
text-decoration: underline;
}`)

	ui.RegisterComponentScript("login", `// Login client scripts`)

	t.Register("login", func(w io.Writer, data any) error {
		if _, err := io.WriteString(w, `<div gs-component="login">
<div class="auth-card">
	<h2>Login</h2>
	<form action="/login" method="POST">
		<input type="hidden" name="_token" value="`); err != nil { return err }
		if _, err := io.WriteString(w, ui.Escape(ui.Evaluate(data, "csrf_token"))); err != nil { return err }
		if _, err := io.WriteString(w, `" />
		<div class="form-group">
			<label>Email Address</label>
			<input type="email" name="email" required placeholder="name@example.com" />
		</div>
		<div class="form-group">
			<label>Password</label>
			<input type="password" name="password" required />
		</div>
		<div class="alert alert-danger">`); err != nil { return err }
		if _, err := io.WriteString(w, ui.Escape(ui.Evaluate(data, "error"))); err != nil { return err }
		if _, err := io.WriteString(w, `</div>
		<button type="submit" class="btn">Sign In</button>
	</form>
	<p class="auth-switch">Don't have an account? <a href="/register">Register</a></p>
</div>
</div>`); err != nil { return err }
		return nil
	})

	ui.RegisterComponentStyle("modal", `gostack-root [gs-component="modal"] .gs-modal-overlay {
position: fixed;
top: 0;
left: 0;
width: 100vw;
height: 100vh;
background-color: rgba(0, 0, 0, 0.5);
display: flex;
align-items: center;
justify-content: center;
z-index: 50;
}
gostack-root [gs-component="modal"] .gs-modal-content {
background-color: #ffffff;
border-radius: 0.5rem;
box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04);
width: 100%;
max-width: 32rem;
padding: 1.5rem;
display: flex;
flex-direction: column;
gap: 1rem;
animation: gs-modal-in 0.2s ease-out forwards;
}
gostack-root [gs-component="modal"] .gs-modal-header {
display: flex;
justify-content: space-between;
align-items: center;
}
gostack-root [gs-component="modal"] .gs-modal-title {
font-size: 1.125rem;
font-weight: 600;
margin: 0;
}
gostack-root [gs-component="modal"] .gs-modal-close {
background: none;
border: none;
font-size: 1.5rem;
line-height: 1;
cursor: pointer;
color: #64748b;
transition: color 0.2s;
}
gostack-root [gs-component="modal"] .gs-modal-close:hover {
color: #0f172a;
}
gostack-root [gs-component="modal"] .gs-modal-body {
font-size: 0.875rem;
color: #475569;
}
gostack-root [gs-component="modal"] .gs-modal-footer {
display: flex;
justify-content: flex-end;
gap: 0.5rem;
margin-top: 0.5rem;
}
gostack-root [gs-component="modal"] .gs-hidden {
display: none !important;
}
@keyframes gs-modal-in {
gostack-root [gs-component="modal"] from {
opacity: 0;
transform: scale(0.95);
}
gostack-root [gs-component="modal"] to {
opacity: 1;
transform: scale(1);
}
}`)

	t.Register("modal", func(w io.Writer, data any) error {
		if _, err := io.WriteString(w, `<div gs-component="modal">
<div gs-component="modal">
    <!-- Overlay -->
    <div class="gs-modal-overlay gs-hidden" id="gs-modal-`); err != nil { return err }
		if _, err := io.WriteString(w, ui.Escape(ui.Evaluate(data, "id"))); err != nil { return err }
		if _, err := io.WriteString(w, `">
        <!-- Modal Dialog -->
        <div class="gs-modal-content">
            <div class="gs-modal-header">
                <h3 class="gs-modal-title">`); err != nil { return err }
		if _, err := io.WriteString(w, ui.Escape(ui.Evaluate(data, "title"))); err != nil { return err }
		if _, err := io.WriteString(w, `</h3>
                <button class="gs-modal-close" gs-click="GoStack.closeModal('`); err != nil { return err }
		if _, err := io.WriteString(w, ui.Escape(ui.Evaluate(data, "id"))); err != nil { return err }
		if _, err := io.WriteString(w, `')">&times;</button>
            </div>
            
            <div class="gs-modal-body">
                `); err != nil { return err }
		if _, err := io.WriteString(w, ui.Escape(ui.Evaluate(data, "content"))); err != nil { return err }
		if _, err := io.WriteString(w, `
            </div>
            
            <div class="gs-modal-footer">
                `); err != nil { return err }
		if _, err := io.WriteString(w, ui.Escape(ui.Evaluate(data, "footer"))); err != nil { return err }
		if _, err := io.WriteString(w, `
            </div>
        </div>
    </div>
</div>
</div>`); err != nil { return err }
		return nil
	})

	ui.RegisterComponentStyle("register", `gostack-root [gs-component="register"] .auth-card {
max-width: 400px;
margin: 50px auto;
padding: 30px;
background: #ffffff;
border-radius: 12px;
box-shadow: 0 4px 20px rgba(0,0,0,0.08);
font-family: 'Inter', sans-serif;
}
gostack-root [gs-component="register"] .auth-card h2 {
margin-top: 0;
margin-bottom: 24px;
color: #1a1a1a;
font-weight: 700;
text-align: center;
}
gostack-root [gs-component="register"] .form-group {
margin-bottom: 20px;
}
gostack-root [gs-component="register"] .form-group label {
display: block;
margin-bottom: 8px;
font-size: 14px;
font-weight: 500;
color: #4a4a4a;
}
gostack-root [gs-component="register"] .form-group input {
width: 100%;
padding: 12px 16px;
border: 1px solid #dcdcdc;
border-radius: 8px;
box-sizing: border-box;
font-size: 15px;
transition: border-color 0.2s;
}
gostack-root [gs-component="register"] .form-group input:focus {
outline: none;
border-color: #4f46e5;
}
gostack-root [gs-component="register"] .btn {
display: block;
width: 100%;
padding: 14px;
background: #4f46e5;
color: #ffffff;
border: none;
border-radius: 8px;
font-size: 16px;
font-weight: 600;
cursor: pointer;
transition: background-color 0.2s;
}
gostack-root [gs-component="register"] .btn:hover {
background: #4338ca;
}
gostack-root [gs-component="register"] .alert {
padding: 12px;
border-radius: 8px;
margin-bottom: 20px;
font-size: 14px;
}
gostack-root [gs-component="register"] .alert:empty {
display: none;
}
gostack-root [gs-component="register"] .alert-danger {
background: #fee2e2;
color: #991b1b;
}
gostack-root [gs-component="register"] .auth-switch {
margin-top: 24px;
text-align: center;
font-size: 14px;
color: #6b7280;
}
gostack-root [gs-component="register"] .auth-switch a {
color: #4f46e5;
text-decoration: none;
font-weight: 500;
}
gostack-root [gs-component="register"] .auth-switch a:hover {
text-decoration: underline;
}`)

	ui.RegisterComponentScript("register", `// Register client scripts`)

	t.Register("register", func(w io.Writer, data any) error {
		if _, err := io.WriteString(w, `<div gs-component="register">
<div class="auth-card">
	<h2>Register</h2>
	<form action="/register" method="POST">
		<input type="hidden" name="_token" value="`); err != nil { return err }
		if _, err := io.WriteString(w, ui.Escape(ui.Evaluate(data, "csrf_token"))); err != nil { return err }
		if _, err := io.WriteString(w, `" />
		<div class="form-group">
			<label>Email Address</label>
			<input type="email" name="email" required placeholder="name@example.com" />
		</div>
		<div class="form-group">
			<label>Password</label>
			<input type="password" name="password" required />
		</div>
		<div class="alert alert-danger">`); err != nil { return err }
		if _, err := io.WriteString(w, ui.Escape(ui.Evaluate(data, "error"))); err != nil { return err }
		if _, err := io.WriteString(w, `</div>
		<button type="submit" class="btn">Create Account</button>
	</form>
	<p class="auth-switch">Already have an account? <a href="/login">Login</a></p>
</div>
</div>`); err != nil { return err }
		return nil
	})

}