// Code generated by GoStack. DO NOT EDIT.
// This file is compiled from component directories during local development builds.

package main

import (
	"fmt"
	"github.com/charledeon77/gostack-framework/framework/http"
	"github.com/charledeon77/gostack-framework/framework/ui"
	"io"
)

// RegisterComponents binds all compiled component views, styles, and scripts.
func RegisterComponents(t *http.Tempose) {
	ui.RegisterComponentStyle("counter", `gostack-root [gs-component="counter"] button {
background-color: #0076ff;
color: white;
border: none;
padding: 0.5rem 1rem;
border-radius: 4px;
cursor: pointer;
}
gostack-root [gs-component="counter"] button:hover {
background-color: #0056b3;
}
gostack-root [gs-component="counter"] span {
font-size: 1.5rem;
margin: 0 1rem;
font-weight: bold;
}`)

	ui.RegisterComponentScript("counter", `// counter.js: Custom reactive handlers or initialization for the counter component
console.log('Counter component hydrated successfully');
`)

	t.Register("counter", func(w io.Writer, data any) error {
		if _, err := io.WriteString(w, `<div gs-component="counter">
<div gs-state='{"count": 0}'>
    <button gs-on:click="count--">-</button>
    <span gs-text="count">0</span>
    <button gs-on:click="count++">+</button>
</div>
</div>`); err != nil { return err }
		return nil
	})

	ui.RegisterComponentStyle("login", `gostack-root [gs-component="login"] .auth-card {
max-width: 400px;
margin: 50px auto;
padding: 30px;
background: #ffffff;
border-radius: 12px;
box-shadow: 0 4px 20px rgba(0,0,0,0.08);
font-family: 'Inter', sans-serif;
}
gostack-root [gs-component="login"] .auth-card h2 {
margin-top: 0;
margin-bottom: 24px;
color: #1a1a1a;
font-weight: 700;
text-align: center;
}
gostack-root [gs-component="login"] .form-group {
margin-bottom: 20px;
}
gostack-root [gs-component="login"] .form-group label {
display: block;
margin-bottom: 8px;
font-size: 14px;
font-weight: 500;
color: #4a4a4a;
}
gostack-root [gs-component="login"] .form-group input {
width: 100%;
padding: 12px 16px;
border: 1px solid #dcdcdc;
border-radius: 8px;
box-sizing: border-box;
font-size: 15px;
transition: border-color 0.2s;
}
gostack-root [gs-component="login"] .form-group input:focus {
outline: none;
border-color: #4f46e5;
}
gostack-root [gs-component="login"] .btn {
display: block;
width: 100%;
padding: 14px;
background: #4f46e5;
color: #ffffff;
border: none;
border-radius: 8px;
font-size: 16px;
font-weight: 600;
cursor: pointer;
transition: background-color 0.2s;
}
gostack-root [gs-component="login"] .btn:hover {
background: #4338ca;
}
gostack-root [gs-component="login"] .alert {
padding: 12px;
border-radius: 8px;
margin-bottom: 20px;
font-size: 14px;
}
gostack-root [gs-component="login"] .alert:empty {
display: none;
}
gostack-root [gs-component="login"] .alert-danger {
background: #fee2e2;
color: #991b1b;
}
gostack-root [gs-component="login"] .auth-switch {
margin-top: 24px;
text-align: center;
font-size: 14px;
color: #6b7280;
}
gostack-root [gs-component="login"] .auth-switch a {
color: #4f46e5;
text-decoration: none;
font-weight: 500;
}
gostack-root [gs-component="login"] .auth-switch a:hover {
text-decoration: underline;
}`)

	ui.RegisterComponentScript("login", `// Login client scripts`)

	t.Register("login", func(w io.Writer, data any) error {
		if _, err := io.WriteString(w, `<div gs-component="login">
<div class="auth-card">
	<h2>Login</h2>
	<form action="/login" method="POST">
		<input type="hidden" name="_token" value="`); err != nil { return err }
		if _, err := io.WriteString(w, fmt.Sprint(ui.Evaluate(data, "csrf_token"))); err != nil { return err }
		if _, err := io.WriteString(w, `" />
		<div class="form-group">
			<label>Email Address</label>
			<input type="email" name="email" required placeholder="name@example.com" />
		</div>
		<div class="form-group">
			<label>Password</label>
			<input type="password" name="password" required />
		</div>
		<div class="alert alert-danger">`); err != nil { return err }
		if _, err := io.WriteString(w, fmt.Sprint(ui.Evaluate(data, "error"))); err != nil { return err }
		if _, err := io.WriteString(w, `</div>
		<button type="submit" class="btn">Sign In</button>
	</form>
	<p class="auth-switch">Don't have an account? <a href="/register">Register</a></p>
</div>
</div>`); err != nil { return err }
		return nil
	})

	ui.RegisterComponentStyle("register", `gostack-root [gs-component="register"] .auth-card {
max-width: 400px;
margin: 50px auto;
padding: 30px;
background: #ffffff;
border-radius: 12px;
box-shadow: 0 4px 20px rgba(0,0,0,0.08);
font-family: 'Inter', sans-serif;
}
gostack-root [gs-component="register"] .auth-card h2 {
margin-top: 0;
margin-bottom: 24px;
color: #1a1a1a;
font-weight: 700;
text-align: center;
}
gostack-root [gs-component="register"] .form-group {
margin-bottom: 20px;
}
gostack-root [gs-component="register"] .form-group label {
display: block;
margin-bottom: 8px;
font-size: 14px;
font-weight: 500;
color: #4a4a4a;
}
gostack-root [gs-component="register"] .form-group input {
width: 100%;
padding: 12px 16px;
border: 1px solid #dcdcdc;
border-radius: 8px;
box-sizing: border-box;
font-size: 15px;
transition: border-color 0.2s;
}
gostack-root [gs-component="register"] .form-group input:focus {
outline: none;
border-color: #4f46e5;
}
gostack-root [gs-component="register"] .btn {
display: block;
width: 100%;
padding: 14px;
background: #4f46e5;
color: #ffffff;
border: none;
border-radius: 8px;
font-size: 16px;
font-weight: 600;
cursor: pointer;
transition: background-color 0.2s;
}
gostack-root [gs-component="register"] .btn:hover {
background: #4338ca;
}
gostack-root [gs-component="register"] .alert {
padding: 12px;
border-radius: 8px;
margin-bottom: 20px;
font-size: 14px;
}
gostack-root [gs-component="register"] .alert:empty {
display: none;
}
gostack-root [gs-component="register"] .alert-danger {
background: #fee2e2;
color: #991b1b;
}
gostack-root [gs-component="register"] .auth-switch {
margin-top: 24px;
text-align: center;
font-size: 14px;
color: #6b7280;
}
gostack-root [gs-component="register"] .auth-switch a {
color: #4f46e5;
text-decoration: none;
font-weight: 500;
}
gostack-root [gs-component="register"] .auth-switch a:hover {
text-decoration: underline;
}`)

	ui.RegisterComponentScript("register", `// Register client scripts`)

	t.Register("register", func(w io.Writer, data any) error {
		if _, err := io.WriteString(w, `<div gs-component="register">
<div class="auth-card">
	<h2>Register</h2>
	<form action="/register" method="POST">
		<input type="hidden" name="_token" value="`); err != nil { return err }
		if _, err := io.WriteString(w, fmt.Sprint(ui.Evaluate(data, "csrf_token"))); err != nil { return err }
		if _, err := io.WriteString(w, `" />
		<div class="form-group">
			<label>Email Address</label>
			<input type="email" name="email" required placeholder="name@example.com" />
		</div>
		<div class="form-group">
			<label>Password</label>
			<input type="password" name="password" required />
		</div>
		<div class="alert alert-danger">`); err != nil { return err }
		if _, err := io.WriteString(w, fmt.Sprint(ui.Evaluate(data, "error"))); err != nil { return err }
		if _, err := io.WriteString(w, `</div>
		<button type="submit" class="btn">Create Account</button>
	</form>
	<p class="auth-switch">Already have an account? <a href="/login">Login</a></p>
</div>
</div>`); err != nil { return err }
		return nil
	})

}